#!/bin/bash

reverse_a_number $1

if [ $? -eq 0 ]
then 
	echo Reversing a number process executed successfully.
else
	echo Reversing a number process execution fails.
fi

sum_of_digits $2

if [ $? -eq 0 ]
then
        echo Sum of the digits process executed successfully.
else
        echo Sum of the digits process execution fails.
fi

