#!/bin/bash

if [ $# -ne 1 ]
then
	echo "WRONG INPUT FORMAT."
	echo "Input format should be : process_name number "
	exit 1
fi

num=$1
k=0
while [ $num -ne 0 ]
do 
	i=`expr $num % 10`
	k=`expr $k \* 10`
	k=`expr $i + $k`
	num=`expr $num \/ 10`
done
echo Reverse of a number : $k

exit 0
