#!/bin/bash

if [ $# -ne 1 ]
then
	echo "WRONG INPUT FORMAT."
	echo "Input format should be : process_name number "
	exit 1
fi

k=0
num=$1
while [ $num -ne 0 ]
do
	j=`expr $num % 10`
	k=`expr $j + $k`
	num=`expr $num \/ 10`
done
echo Sum of Digits: $k

exit 0
